services:

  # CONTAO HOOKS:
  # Contao add parse articles hook
  Markocupic\ContaoNewsInfiniteScrollBundle\EventListener\Contao\ParseArticlesListener:
    public: true
    arguments:
    - "@contao.framework"
    tags:
    - { name: kernel.event_listener, event: contao.parse_articles, method: addCanonicalTag }

